services:
  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.9.0
    container_name: kibana
    depends_on:
      - elasticsearch
    networks:
      - elk
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # 先启动elasticsearch，获得passwd后再启动kibana
      - ELASTICSEARCH_USERNAME="kibana_system"
      - ELASTICSEARCH_PASSWORD="+H_4cZBF3xgXTYo3k7Q*"  # 替换为实际密码

networks:
  elk:
    driver: bridge

volumes:
  es-data:
    driver: local